import React  from 'react';
import './Content.min.css';

function Content() {
    return (
        <p className="content">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni laudantium non, blanditiis, officia, placeat nam deserunt beatae dolore sunt reprehenderit architecto? Animi, temporibus atque? Nulla dicta sint ex velit deserunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, exercitationem quidem aliquam blanditiis quibusdam cumque voluptate, repudiandae aliquid officiis beatae explicabo recusandae alias. Quam earum ducimus commodi quia, minus minima. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique a officiis minus tempora inventore quidem est, perferendis ipsa magnam veniam accusamus sit ratione natus aspernatur porro architecto fugiat magni nostrum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum eos dolores rerum accusamus corporis illo voluptatum, eum non iusto. Vitae hic nam at neque dolore? Facilis, explicabo repellat. Quos, explicabo. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Unde, quae corrupti veritatis fugit aut fuga deserunt? Sed ratione cupiditate voluptatibus reiciendis eveniet beatae id reprehenderit molestias, doloribus deserunt voluptas eius! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, praesentium! Aperiam, nostrum! Cumque hic ea eveniet impedit nihil sit minima delectus, eligendi at asperiores expedita ipsum voluptate accusantium perspiciatis facere. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa sit, officia et commodi fuga impedit doloremque, molestias, facere nemo voluptatum ipsa neque illo? Aut error, veniam ipsam repellat quo dolor! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Necessitatibus, voluptas magni. Cupiditate, autem laudantium iusto commodi sapiente nisi, mollitia, ad adipisci nostrum temporibus eos sunt porro perspiciatis rem perferendis optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quidem sequi atque recusandae libero voluptatem excepturi, deserunt perspiciatis quo asperiores illo enim corporis minus quia animi ab veniam ipsum fuga! Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum cupiditate perferendis suscipit esse voluptates reprehenderit quas tenetur, similique veniam velit quam soluta ab accusantium repellat temporibus? Aspernatur, deleniti soluta? Distinctio!
        </p>
    )
}

export default Content;